### ISSUE TITLE
TS0601 "_TZE200_aqnazj70" Problem with the fourth button not reporting state change on press

### ISSUE THREAD

**Issue by oferwald** [Koenkk/zigbee-herdsman-converters#2142] opened 2021-01-23 23:51 UTC
I have this 4gang tuya switch.
https://www.aliexpress.com/item/4001181765345.html
(The EU version from this link)

The bug is simple and annoying, every button press is recorded in zigbee2mqtt, except the 4th button which is not responding (no event is generated) just to make clear, this is the right bottom button on the switch

When I set the state of the button from HA this works correctly. (turning it on and off toggles the switch)

This has also been reported in the following link: (see last few comments)
https://github.com/Koenkk/zigbee2mqtt/issues/5156

I have a similar issue with this TS0601 (_TZE200_aqnazj70) which is the US version of the same switch. bought from the same store and link.

Let me know if any further information is needed.

**Comment by Koenkk** [comment] 2021-01-24 17:56
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/4597

**Closed by Koenkk** 2021-01-24 17:56 UTC
