### ISSUE TITLE
PI Heating Demand on Sinope TH1223ZB incorrectly controlling running state

### ISSUE THREAD

**Issue by crbn60** [Koenkk/zigbee-herdsman-converters#3510] opened 2021-12-13 18:52 UTC
I have a Sinopé TH1223ZB thermostat which is currently reporting state:
```json
{
    "current": 6962,
    "keypad_lockout": 0,
    "linkquality": 255,
    "local_temperature": 18,
    "occupied_heating_setpoint": 19,
    "operation": "heating",
    "pi_heating_demand": 16,
    "running_mode": "heat",
    "running_state": "heat",
    "system_mode": "heat",
    "voltage": 1206
}
```

However the heater is not running. Seems like `running_state` is [calculated](https://github.com/Koenkk/zigbee-herdsman-converters/blob/10f29e0be3aad30807c0e469e4095ef5c58b4d0c/lib/legacy.js#L1849) from `pi_heating_demand >= 10`  which does not appear to be correct for at least this model. I'm watching to see exactly what it _should_ be.

I tested using Docker image tagged `latest-dev` and have `legacy: false` on the device settings.

**Comment by crbn60** [comment] 2021-12-13 19:26
Believe the correct place to get this data is from:
```
'hvacThermostat': {"runningState":1}
```
Appears to be simply 0 or 1.

**Comment by crbn60** [comment] 2021-12-13 19:35
This was likely broken by the fix to #2738.

@embak the TH1123ZB that I have appears to report running state:

![image](https://user-images.githubusercontent.com/1441946/145876388-6dbde31c-88e7-42f1-b868-cfe4f04b7fd0.png)

But the [code](https://github.com/Koenkk/zigbee-herdsman-converters/blob/10f29e0be3aad30807c0e469e4095ef5c58b4d0c/lib/legacy.js#L1849) in legacy.js is overwriting it. Do you thing that is correct?

Or, despite me having `legacy` set to `false`, is that the problem?

**Comment by crbn60** [comment] 2021-12-13 22:15
The more I dig, the more I think this issue is that the `legacy` property appears to not be honoured.

**Comment by embak** [comment] 2021-12-14 06:56
#2738 fixed 2 things.
1) Ask the thermostat to report changes of Zigbee _hvacThermostat->runningState_
2) Correct the deprecated  MQTT _state->operation_ by adding MQTT _state->running_state_ ("idle", "heat") based on Zigbee _hvacThermostat->piHeatingDemand_ (0, 1).

@crbn60 , My findings on this issue are:

**Problem with MQTT _state->pi_heating_demand_**
When investigating this issue with my TH1124ZB, I discovered that when Zigbee _hvacThermostat->piHeatingDemand_ = 100 the MQTT state->pi_heating_demand = 39 . It seems that Zigbee _hvacThermostat->piHeatingDemand_ is scaled from 256 to 100 when it shouldn't. There is a problem here. 

**Need to adjust MQTT _state->running_state_ based on support of Zigbee _hvacThermostat->runningState_ reporting.**
The main reason MQTT _state->running_state_ is based on Zigbee _hvacThermostat->piHeatingDemand_ is because older firmware didn't support the Zigbee _hvacThermostat->runningState_ reporting. If possible, a fix will be required to differentiate between those that have it and others that don't.  Fixing the previous problem will also improve this. 
BTW, there is no relation with the Zigbee2mqtt _legacy_ configuration option

**Instability of Sinope Zigbee __hvacThermostat->runningState_**
During testing I notice a lot of change (instability between polling) of Zigbee _hvacThermostat->runningState , Such instability  could generate a lot of traffic on the Zigbee network. The actual reporting has a minimum interval set to 0 seconds. On a network with 10-15 thermostats like mine, this means a lot of traffic when trottling home temperature in the winter. A fix will be required to reduce the occurrence of those reports.  A minimum of 10 seconds between updates should do it.
In _sinope.js_ , replacing all occurence:
    await reporting.thermostatRunningState(endpoint);
by: 
    await reporting.thermostatRunningState(endpoint , {min: 10, max: 302, change: 1});


@Koenkk, my developement setup is not operational.
Can-you help on this ?
Also, how can I activate the loging of incoming Zigbee packets (I really miss this feature) ?

**Comment by crbn60** [comment] 2021-12-14 16:11
Thank you very much for taking the time to write such an in-depth reply @embak !

> Need to adjust MQTT state->running_state based on support of Zigbee hvacThermostat->runningState reporting.
> The main reason MQTT state->running_state is based on Zigbee hvacThermostat->piHeatingDemand is because older firmware didn't support the Zigbee hvacThermostat->runningState reporting. If possible, a fix will be required to differentiate between those that have it and others that don't. Fixing the previous problem will also improve this.

I _believe_ my TH1223ZB unit, which displays `0.6.5` on startup and z2m shows as running firmware `2051` correctly reports `hvacThermostat->runningState`. Trying to correlate the value of `hvacThermostat->piHeatingDemand` with whether or not it actually closes the circuit to the heater has proven quite difficult, however. It seems to be all over the map. These graphs show when the heater is on (using the inverter output) and what it was reporting for heating demand:

![Graphs](https://www.evernote.com/l/ACWobt2rHYhJf5OXiWgKJtC58VkMiJp1xj8B/image.png)

> BTW, there is no relation with the Zigbee2mqtt legacy configuration option

Good to know, thank you for confirming.

> During testing I notice a lot of change (instability between polling) of Zigbee _hvacThermostat->runningState , Such instability could generate a lot of traffic on the Zigbee network. The actual reporting has a minimum interval set to 0 seconds.

What can I do to confirm that this is _not_ the case with my unit?

> ---- my developement setup is not operational.

I'm using a Docker image managed via [balenaCloud](https://www.balena.io/cloud/) to run z2m. What is the wise way to test code changes for me?

**Comment by crbn60** [comment] 2021-12-14 16:13
Forgot to mention: I reached out to Sinopé and was told the latest firmware version is `0.6.8` and that the device has "two firmwares". One is not updatable and the other can only be updated using their proprietary hub.

**Comment by embak** [comment] 2021-12-15 03:38
My TH1124ZB firmwares are version 1497 (date 20190329). This firmware doesn't support Zigbee _hvacThermostat->runningState reporting.

![image](https://user-images.githubusercontent.com/16234456/146108123-b5162324-e339-41e4-a9f5-6c431ead27da.png)


Can-you try on your side to add reporting using z2m GUI?

Regarding the  Zigbee _hvacThermostat->runningState stability, you can first set the thermostat setpoint to a higher value and then frequently (every 2-3 seconds) poll _hvacThermostat->runningState.

![image](https://user-images.githubusercontent.com/16234456/146112522-f01aa08b-9c21-460a-8031-46976c4a7b2e.png)

When I do this runningState toggle frequently ( 0 <-> 1) between polls. 

Looking at the origin of Sinope TH1123ZB and TH1124ZB z2m implementations most parameters where extracted from Smarthing configuration files. There is no Zigbee _hvacThermostat->runningState used. The confusing similar MQTT state->running_state was forged from piHeatingdemand for HASS HVAC compatibility.  BTW this is the same implementation for Stelpro baseboards.

**Comment by crbn60** [comment] 2021-12-16 01:01
I also receive the `UNREPORTABLE_ATTRIBUTE` when attempting to add reporting. Yet I can retrieve it via the Dev Console? I don't understand enough…

Polling for the parameter appears perfectly stable in my case, in either direction.

What's the best way for me to make small changes and deploy them? Should I setup a personal docker hub and push my forked builds to it?

Thanks for your continued interest in this @embak , I really appreciate it.

**Comment by crbn60** [comment] 2021-12-16 02:18
Just caught this in the logs:
```
Zigbee2MQTT:debug 2021-12-15 21:06:13: Device 'ctrlThermostat' requested OTA
[Logs]    [12/15/2021, 9:06:21 PM] [zigbee2mqtt] Zigbee2MQTT:debug 2021-12-15 21:06:21: Received Zigbee message from 'ctrlThermostat', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":37814528,"imageType":4389,"manufacturerCode":4508}' from endpoint 1 with groupID null
```
Would it be difficult to figure OTA updates out?

**Comment by embak** [comment] 2021-12-16 03:31
> I also receive the UNREPORTABLE_ATTRIBUTE when attempting to add reporting. Yet I can retrieve it via the Dev Console? I don't understand enough…

There is a fundamental difference. In Zigbee you get cluster attributes values from your end device by either:
1. "Polling". This is initiated on demand by another device. To my knolledge z2m is event driven so pooling need to be initiated by an external application trough MQTT commands. This is what you do when using the Dev Console. The unknown is polling interval to use.
2. "Reporting". The end device is configured to send data based on value change (hysterisis) with a minimum and maximum interval. z2m software received the data and publish-it to MQTT.

Since Zigbee _hvacThermostat->runningState_ reporting is not supported by your thermostat, you need to do periodic polling if you want that attribute. This also means more traffic on the zigbee network.

What exactly do you want to do ?

IMHO you should use the rmsCurrent and tweek the default reporting interval min/max + hysteresis from the z2m GUI.

> Just caught this in the logs:
```
Zigbee2MQTT:debug` 2021-12-15 21:06:13: Device 'ctrlThermostat' requested OTA
[Logs]    [12/15/2021, 9:06:21 PM] [zigbee2mqtt] Zigbee2MQTT:debug 2021-12-15 21:06:21: Received Zigbee message from 'ctrlThermostat', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":37814528,"imageType":4389,"manufacturerCode":4508}' from endpoint 1 with groupID null
```
> Would it be difficult to figure OTA updates out?

I also saw that in log messages in the past. The thermostat querry for update every few hours.
The problem is to get the firmware from Sinope. Previous search on other forums was not successfull. There is non-negligeable chance to brick the thermostat.  Also, there is no guarantee the feature you are looking at will be in that firmware.

**Comment by crbn60** [comment] 2021-12-16 04:33
My principle goal is to trigger an auxiliary heater and/or a fan when the
primary heater is running, using the heating demand variable to make some
decisions.

I will check if rmsCurrent is accurately reporting, right now.
-- 
Adam Sherman
+1 613 797 6819

**Comment by crbn60** [comment] 2021-12-16 05:29
I cannot seem to get the haElectricalMeasurement->rmsCurrent attribute to report regularly:
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/1441946/146313537-61f02101-f6df-4460-b1b0-a05e5a04e070.png">
Seems to send it just on occasion.

**Comment by crbn60** [comment] 2021-12-16 05:31
I also just noticed that polling the value is returning bogus numbers:
```
Read result of 'haElectricalMeasurement': {"rmsCurrent":491}
```
The heater is completely off at the point this was noted, as measured by the Victron inverter (which is trustworthy).

Maybe this thermostat is just crap and I should stop banging my head against it?

**Comment by embak** [comment] 2021-12-16 13:13
This is not a bogus number. You need to apply a scaling factor to convert Zigbee _hvacThermostat->rmcCurrent_ integer value to Arms. Z2M already do it for you. Look at the MQTT_State->current_ value. Z2M Gui Dev pannel is for developping and debugging.

What is your expected delay between the thermostat turn-on / turn-off and MQTT _State->current_ update ?

If you want to do a real test, use a curent clamp and connect-it to a multimeter or a scope.

BTW Sinope thermostats are excellent baseboard and floor heating thermostats. They do what they need to do.

**Comment by crbn60** [comment] 2021-12-16 14:25
> This is not a bogus number. You need to apply a scaling factor to convert Zigbee hvacThermostat->rmcCurrent integer value to Arms. Z2M already do it for you. Look at the MQTT_State->current_ value. Z2M Gui Dev pannel is for developping and debugging.

Are you sure? Because the state tab shows the same value, as does what I pull via MQTT into Node-RED. I thought it was simply milliamps. I've seen it in the 400, 3500, and 7000 ranges. And the heater should draw around 6.25A pretty consistently, I'd expect. Might something to do with the "long cycle" setting used with the fan-type heater?

> What is your expected delay between the thermostat turn-on / turn-off and MQTT State->current update ?

Since I want to control other things using the heater state, I'd really like it to be less than 60 seconds.

Something I don't fully understand is that, right this moment:
- Z2M frontend "State" tab shows `current: 0`; (it went to `702` as I was proof-reading this post, maybe because I read the attribute?)
- MQTT topic is showing `6962`.
- Z2M dev consol reads `{"rmsCurrent":702}`. (As above, changed to `702`.)
- The heater is using no current as measured directly at the battery.

> If you want to do a real test, use a curent clamp and connect-it to a multimeter or a scope.

The only power to this heater comes from my LFP battery bank (through the inverter), so it's pretty easy to watch its current draw.

**Comment by crbn60** [comment] 2021-12-16 17:24
Further discussion with @embak has led met to attempt a different approach:

- Watch the heating demand parameter.
- If demand stays @ 100% for > a certain time (say 5 minutes), engage auxiliary heater for a certain time (say 15 minutes)

This doesn't help me know when to be running the ceiling fan to help maintain even temperature distribution, but it is a start.

**Comment by crbn60** [comment] 2021-12-16 21:54
Speaking of the scaling of attributes reported @embak , is this correct in the z2m frontend?
<img width="350" alt="image" src="https://user-images.githubusercontent.com/1441946/146454655-977a250b-05b1-45f1-9d61-58eaf2b05ca8.png">

**Comment by embak** [comment] 2021-12-16 22:55
Here is what I get:

![image](https://user-images.githubusercontent.com/16234456/146459825-843a987b-9b1f-4db2-8604-d75a279dc101.png)

There is something wrong with your setup. It seems that z2m didn't receive any scaling factors from your thermostats in the initial pairing process.

I suggest that you:
1) Enable the log at the debug level
2) Clear the z2m database.db file.
3) Restart z2m
4) Repair your thermostat with your zigbee router using Sinope's procedure.

In the logs you will see all the steps that z2m do to interrogate your device including the querry for the electrical measurements  divisors.

**Comment by embak** [comment] 2021-12-16 23:07
Regarding reported attributes updates. 

![image](https://user-images.githubusercontent.com/16234456/146461334-676ae558-9b22-4c42-bacf-ec5350625038.png)

You need to lower the max rep interval to get an update when the value change bellow the min rep range. This is more relevent in your case when you want to know when the thermostat is turning off. On your screen shot, it will take 3600 seconds !

If your thermostat was paired as expected, z2m would have set the max rep interval to 306 seconds (~5 min). This is the optimal value for a residential use with multiple thermostats on the same network.

**Comment by crbn60** [comment] 2021-12-17 00:47
Might be a deconz problem:
```
Error Failed to configure 'ctrlThermostat', attempt 1 (Error: Bind 0x500b91400002927f/1 genBasic from '0x00212effff065dfb/1' failed (waiting for response TIMEOUT) at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:753:19) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:517:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:9) at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/sinope.js:31:13) at Configure.configure (/app/lib/extension/configure.ts:115:13))
```

**Comment by crbn60** [comment] 2021-12-19 15:15
I've ordered a better Zigbee USB controller and will revisit this.

**Comment by embak** [comment] 2021-12-20 03:29
PR #3551 will fix the current and voltage scaling problem you have with TH1123ZB.

**Comment by crbn60** [comment] 2021-12-20 19:52
> PR #3551 will fix the current and voltage scaling problem you have with TH1123ZB.

Looks much better here:
```json
{
    "current": 7.03,
    "linkquality": 255,
    "local_temperature": 18.64,
    "occupied_heating_setpoint": 18.5,
    "operation": "heating",
    "pi_heating_demand": 71,
    "running_state": "heat",
    "system_mode": "heat",
    "voltage": 120,
    "energy": 77.38
}
```

**Comment by crbn60** [comment] 2022-01-20 19:15
Do you intend to change the runningState reporting or should this issue just be closed?

**Comment by embak** [comment] 2022-01-21 01:42
As mentionned, the thermostat don't support self reporting of runningState. This issue should be closed.

**Closed** 2022-01-21 17:41 UTC
