### ISSUE TITLE
Power metering support for SP600 not working for newly paired devices

### ISSUE THREAD

**Issue by davet2001** [Koenkk/zigbee-herdsman-converters#848] opened 2019-12-27 08:11 UTC
Power metering not working for SP600 devices if I re-pair them, see issue https://github.com/Koenkk/zigbee2mqtt/issues/2352.

I have a fix for this and will submit a PR.

**Comment by davet2001** [comment] 2019-12-27 08:26
PR created: 
https://github.com/Koenkk/zigbee-herdsman-converters/pull/849

**Comment by Koenkk** [comment] 2019-12-27 08:30
Merged, thanks!

**Closed by Koenkk** 2019-12-27 08:30 UTC

**Comment by PedroLamas** [comment] 2020-01-11 21:16
@Koenkk Since this got merged, my SP600 is now reporting the power 10x higher than it should, so I think this fixed the [other issue](https://github.com/Koenkk/zigbee-herdsman-converters/issues/726) for which we added the specific converter!

I'm going to replace the `fz.SP600_power` with `fz.generic_power` and see if that fixes it.

**Comment by PedroLamas** [comment] 2020-01-11 21:26
Confirmed: changing to `fz.generic_power` now shows with correct power (so it now uses the multiplier)!!

I'll be opening a PR in a few minutes with this single change!

**Comment by PedroLamas** [comment] 2020-01-11 21:43
PR #898 created to fix the new problem.
