### ISSUE TITLE
_TZE204_r0jdjrvi does not support functions from TS0601_cover_1

### ISSUE THREAD

**Issue by andrejsoucek** [Koenkk/zigbee-herdsman-converters#6517] opened 2023-11-20 12:15 UTC
TS0601_cover_1 exposes motor speed and reverse direction. The _TZE204_r0jdjrvi device does not. Pairing is done differently than described in the z2m documentation (three short presses and one long).

This MR added the device as TS0601_cover_1: https://github.com/Koenkk/zigbee-herdsman-converters/pull/5708

I don't have tuya gateway but I might be able to guess the datapoints and prepare a converter. I hope it will support setter for position.

**Comment by andrejsoucek** [comment] 2023-11-20 12:25
@darki73 does your device work correctly with TS0601_cover_1?

**Comment by darki73** [comment] 2023-12-05 07:41
@andrejsoucek Hi, sorry for the late response, been a tough couple of weeks.

I've ended up with writing a manual converter for this device as it sometimes just fails to report it's states and seems like required to boot off with the simplest controlls.

This is what i've been using for the past couple of months, as the fix i've suggested works at most half of the time.

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const presets = exposes.presets;
const access = exposes.access;


const definition = {
    fingerprint: [
        {
            modelID: 'TS0601',
            manufacturerName: '_TZE204_r0jdjrvi'
        }
    ],
    model: 'TS0601_lilistore',
    vendor: 'TuYa',
    description: 'lilistore Tuya ZigBee Motorized Curtain Roller',
    fromZigbee: [
        legacy.fromZigbee.tuya_cover, 
        fz.ignore_basic_report
    ],
    toZigbee: [
        legacy.toZigbee.tuya_cover_control, 
        legacy.toZigbee.tuya_cover_options
    ],
    exposes: [
        presets.cover_position().setAccess('position', access.STATE_SET),

        exposes
            .composite('options', 'options', access.STATE_SET)
                .withFeature(
                    exposes.binary('reverse_direction', access.STATE_SET, true, false)
                        .withDescription('Reverse the motor direction')
                ),
    ]
};

module.exports = definition;
```

Even with this code, sometimes it fails to report the ability to reverse the direction of the motor, but after a couple of power off / on cycles it starts to work just fine.

**Comment by andrejsoucek** [comment] 2023-12-05 08:57
@darki73 that's sad...anyway I can live with that I guess, I just need to be able to set position (or at least 0%, 50%, 100%). I still haven't figured out if the motor remembers where the minimum and maximum is or it just goes until it gets blocked. I will try your converter, thank you.

**Comment by darki73** [comment] 2023-12-07 07:25
@andrejsoucek The motor just goes until it is unable to go no more. Issue with that, the rating for Nm on the motor is incorrect, mine presented as 3Nm, but in fact, it is unable to move the curtain which was moved by the motor with the 2Nm motor. Well, it moves, but really struggles for the last meter or so. 

Position setting works just fine, here is the automation i use to open main shades in the bedroom to 50% at 9 am:
```yaml
- alias: Open Bedroom Main Shades at Sunrise
  description: ""
  trigger:
    - platform: time
      at: "09:00:00"
  condition: []
  action:
    - service: cover.set_cover_position
      data:
        position: 50
      target:
        entity_id: cover.bedroom_main_shades
  mode: single
```

So no issues here. Just a note, first you need to manually drag the curtain in either close / open position, then in the Z2M you need to toggle "reverse_motor" if the reported state does not match as the motor itself seems to have no idea which way is open by default and which is closed.

**Comment by andrejsoucek** [comment] 2023-12-07 07:41
@darki73 thanks, I have the same issue with unsufficient strength, I am using two of these motors to open my pergola roof. The roof is split into 2 parts, one part is fine, the closing is slower than opening because it needs to pull the slats but it closes fine. The second part actually gets stuck in most cases while in the middle of closing. So I 3D printed a planetary gear box which is now really powerful and I need to somehow tell the motor to stop or it will either break the pergola or the gearbox. :laughing: 
But the roof is now closed and motor shows position 0. So once it gets stuck on the other "end" (in fully open position) it should show 100 and it's done. I want to test it ASAP but there is snow on the roof right now... :snowflake: :grimacing:

**Comment by darki73** [comment] 2024-01-02 15:10
@andrejsoucek 

Well, i've went over all the hoops to get it to the state it actually works with all the datapoints and here is the final result:
```js
const tuya = require('zigbee-herdsman-converters/lib/tuya')
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const exposesPresets = exposes.presets;
const exposesAccess = exposes.access;

module.exports = {
    fingerprint: tuya.fingerprint('TS0601', ['_TZE204_r0jdjrvi']),
    model: 'TS0601_lilistore',
    vendor: 'TuYa',
    description: 'lilistore Tuya ZigBee Motorized Curtain Roller',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    onEvent: tuya.onEventSetTime,
    options: [exposes.options.invert_cover()],
    configure: tuya.configureMagicPacket,
    exposes: [
        exposesPresets.cover_position().setAccess('position', exposesAccess.STATE_SET),
        exposesPresets.enum('reverse_direction', exposesAccess.STATE_SET, ['forward', 'back']).withDescription('Reverse the motor direction'),
        exposesPresets.binary('motor_fault', exposesAccess.STATE, true, false).withDescription('Motor Fault'),
    ],
    whiteLabel: [
        tuya.whitelabel('Lilistore', 'TS0601_lilistore', 'Cover motor', ['_TZE204_r0jdjrvi']),
    ],
    meta: {
        tuyaDatapoints: [
            [1, 'state', tuya.valueConverterBasic.lookup({'OPEN': tuya.enum(0), 'STOP': tuya.enum(1), 'CLOSE': tuya.enum(2), 'CONTINUE': tuya.enum(3)})],
            [2, 'position', tuya.valueConverter.coverPosition],
            [3, 'position', tuya.valueConverter.raw],
            [5, 'reverse_direction', tuya.valueConverterBasic.lookup({'forward': tuya.enum(0), 'back': tuya.enum(1)})],
            [12, 'motor_fault', tuya.valueConverter.trueFalse1],
        ],
    }
};
```

Now, these datapoints are extracted from the TuYa IOT Cloud, not using `legacy` anymore, and now the motor direction actually works as intended (i guess they've changed something, as now it only supports `forward` and `back` as strings instead of `true` and `false`.

For some reason, it even started to work a bit faster (no more strange delays between command issued and action performed).

Sadly, this motor only supports basic set of functions, there is no limits, no nothing, just open / close / set position.

Side note, in the 
```
exposesPresets.cover_position().setAccess('position', exposesAccess.STATE_SET),
```
motor straight up refuses to work without `.setAccess('position', exposesAccess.STATE_SET)`, even though the examples in the officially supported devices work without it, so it is kinda needed.

**Comment by andrejsoucek** [comment] 2024-01-02 23:22
@darki73 thanks for this, are you going to put it to a merge request?

**Comment by darki73** [comment] 2024-01-04 12:38
@andrejsoucek Hey, i made a PR https://github.com/Koenkk/zigbee-herdsman-converters/pull/6830

It should remove the invalid assignment made by the https://github.com/Koenkk/zigbee-herdsman-converters/pull/5708 and should work as expected.

There are some changes i made to the code as the original code somewhat failed to work with the HA cards (they were not getting the proper state, but everything was working fine through the automations).

As of now, while it is not yet merged, the following code should work just fine:
```js
const tuya = require('zigbee-herdsman-converters/lib/tuya')
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const exposesPresets = exposes.presets;
const exposesAccess = exposes.access;

module.exports = {
    fingerprint: tuya.fingerprint('TS0601', ['_TZE204_r0jdjrvi']),
    model: 'TS0601_lilistore',
    vendor: 'TuYa',
    description: 'lilistore Tuya ZigBee Motorized Curtain Roller',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    onEvent: tuya.onEventSetTime,
    options: [exposes.options.invert_cover()],
    configure: tuya.configureMagicPacket,
    exposes: [
        exposesPresets.cover_position().setAccess('position', ea.STATE_SET),
        exposesPresets.enum('reverse_direction', exposesAccess.STATE_SET, ['forward', 'back']).withDescription('Reverse the motor direction'),
        exposesPresets.binary('motor_fault', exposesAccess.STATE, true, false).withDescription('Motor Fault'),
    ],
    whiteLabel: [
        tuya.whitelabel('Lilistore', 'TS0601_lilistore', 'Cover motor', ['_TZE204_r0jdjrvi']),
    ],
    meta: {
        tuyaDatapoints: [
            [1, 'state', tuya.valueConverterBasic.lookup({'OPEN': tuya.enum(0), 'STOP': tuya.enum(1), 'CLOSE': tuya.enum(2)})],
            [2, 'position', tuya.valueConverter.coverPositionInverted],
            [3, 'position', tuya.valueConverter.coverPositionInverted],
            [5, 'reverse_direction', tuya.valueConverterBasic.lookup({'forward': tuya.enum(0), 'back': tuya.enum(1)})],
            [12, 'motor_fault', tuya.valueConverter.trueFalse1],
        ],
    }
};
```

**Closed** 2024-01-04 15:10 UTC

**Comment by kabturek** [comment] 2024-03-07 11:14
Thanks for the work guys. I have the same motor and i'm not sure if i have a defective one or going crazy - mine doesn't want to connect through any zigbee router  - when it's close to the coordinator it works fine. when i put it in the final position (1m from an ikea zigbee bulb and many other routers in sight) it stops working "Failed to ping etc". I've left it for couple of hours there and nothings happens. @darki73 @andrejsoucek are your motors directly connected to the coordinator ?

**Comment by darki73** [comment] 2024-03-08 07:13
@kabturek Hey, 1 directly (gypsum wall), and two are through set of phillips plugs (3 between motor and coordinator), work just fine, mine though is a sonoff (I guess) usb plus with external antenna

**Comment by darki73** [comment] 2024-03-11 07:46
@kabturek 

Here is the USB dongle - SONOFF Zigbee 3.0 USB Dongle Plus V2

And here is the map, for the Bedroom Shades
<img width="400" alt="Screenshot 2024-03-11 at 11 45 26" src="https://github.com/Koenkk/zigbee-herdsman-converters/assets/1318627/df22d3c2-2a0f-41b1-b499-8658b0240a38">
