### ISSUE TITLE
Please add Namron 1402769 Zigbee LED Dimmer

### ISSUE THREAD

**Issue by Joernos** [Koenkk/zigbee-herdsman-converters#5766] opened 2023-05-20 14:20 UTC
Hei.
Just bought a Namron 1402769 Zigbee LEd Dimmer. Unfortunately it was not supported. I see there is a similar Namron dimmer with modelname 1402755 that is supported. Is it possible to have the new model added?

https://www.namron.com/no/produkter/namron-zigbee-led-dimmer-250w/

Thank you very much in advance. 

I tried to add it manually but I wasn't able to make it work.

**Comment by Koenkk** [comment] 2023-05-26 07:17
Could you check if the issue is fixed with the following external converter: https://gist.github.com/Koenkk/97687a5fe170ed4472946ef7533a4172

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by tobiaspedersen** [comment] 2023-05-26 15:05
Thank you. After a short test it looks like it is working as It should

**Comment by Koenkk** [comment] 2023-05-26 15:20
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Closed by Koenkk** 2023-05-26 15:20 UTC
