### ISSUE TITLE
Eurotronic Spirit SPZB0001 gives INVALID_VALUE response

### ISSUE THREAD

**Issue by heggink** [Koenkk/zigbee-herdsman-converters#1714] opened 2020-10-29 21:00 UTC
Just paired brand new SPZB0001. Recognised fine but control not workinng. Any command sent to the thermostat results in an INVALID_RESPONSE error:

```
info  2020-10-29 17:31:58: Device '0x00158d00053d2679' is supported, identified as: Eurotronic Spirit Zigbee wireless heater thermostat (SPZB0001)
info  2020-10-29 17:31:58: Configuring '0x00158d00053d2679'
info  2020-10-29 17:31:58: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"Spirit Zigbee wireless heater thermostat","friendly_name":"0x00158d00053d2679","model":"SPZB0001","supported":true,"vendor":"Eurotronic"},"type":"pairing"}'
{"dateCode":"20191014","description":"Spirit Zigbee wireless heater thermostat","friendly_name":"0x00158d00053d2679","hardwareVersion":35,"ieeeAddr":"0x00158d00053d2679","lastSeen":1603989146503,"manufacturerID":4151,"manufacturerName":"Eurotronic","model":"SPZB0001","modelID":"SPZB0001","networkAddress":8287,"powerSource":"Battery","softwareBuildID":"22190930","type":"EndDevice","vendor":"Eurotronic"}],"type":"devices"}'

okt 29 21:20:09 domoticz npm[22834]: Zigbee2MQTT:debug 2020-10-29 21:20:09: Received MQTT message on 'zigbee2mqtt/KA Thermostaat/set' with data '{"current_heating_setpoint": 20.0}'
okt 29 21:20:09 domoticz npm[22834]: Zigbee2MQTT:debug 2020-10-29 21:20:09: Publishing 'set' 'current_heating_setpoint' to 'KA Thermostaat'
okt 29 21:20:12 domoticz npm[22834]: Zigbee2MQTT:error 2020-10-29 21:20:12: Publish 'set' 'current_heating_setpoint' to 'KA Thermostaat' failed: 'Error: Write 0x00158d00053d2679/1 hvacThermostat({"16387":{"value":2000,"type":41}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null}) failed (Status 'INVALID_VALUE')'
okt 29 21:20:12 domoticz npm[22834]: Zigbee2MQTT:debug 2020-10-29 21:20:12: Error: Write 0x00158d00053d2679/1 hvacThermostat({"16387":{"value":2000,"type":41}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null}) failed (Status 'INVALID_VALUE')
okt 29 21:20:12 domoticz npm[22834]:     at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:173:23)
okt 29 21:20:12 domoticz npm[22834]:     at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:202:26)
okt 29 21:20:12 domoticz npm[22834]:     at Generator.next (<anonymous>)
okt 29 21:20:12 domoticz npm[22834]:     at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58)


okt 29 21:49:58 domoticz npm[22834]: Zigbee2MQTT:debug 2020-10-29 21:49:58: Publishing 'set' 'system_mode' to 'KA Thermostaat'
okt 29 21:49:59 domoticz npm[22834]: Zigbee2MQTT:debug 2020-10-29 21:49:59: Received Zigbee message from 'KA Thermostaat', type 'readResponse', cluster 'hvacThermostat', data '{"16392":1}' from endpoint 1 with groupID 0
okt 29 21:49:59 domoticz npm[22834]: Zigbee2MQTT:info  2020-10-29 21:49:59: MQTT publish: topic 'zigbee2mqtt/KA Thermostaat', payload '{"current_heating_setpoint":21,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"eurotronic_system_mode":1,"linkquality":108,"local_temperature":20.5,"occupied_heating_setpoint":21,"system_mode":"auto","unoccupied_heating_setpoint":16}'
okt 29 21:49:59 domoticz npm[22834]: Zigbee2MQTT:debug 2020-10-29 21:49:59: eurotronic: host_flags object converted to 33
okt 29 21:49:59 domoticz npm[22834]: Zigbee2MQTT:error 2020-10-29 21:49:59: Publish 'set' 'system_mode' to 'KA Thermostaat' failed: 'Error: Write 0x00158d00053d2679/1 hvacThermostat({"16392":{"value":33,"type":34}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null}) failed (Status 'INVALID_VALUE')'
okt 29 21:49:59 domoticz npm[22834]: Zigbee2MQTT:debug 2020-10-29 21:49:59: Error: Write 0x00158d00053d2679/1 hvacThermostat({"16392":{"value":33,"type":34}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null}) failed (Status 'INVALID_VALUE')
okt 29 21:49:59 domoticz npm[22834]:     at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:173:23)
okt 29 21:49:59 domoticz npm[22834]:     at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:202:26)
okt 29 21:49:59 domoticz npm[22834]:     at Generator.next (<anonymous>)
okt 29 21:49:59 domoticz npm[22834]:     at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58)
okt 29 21:49:59 domoticz npm[22834]: Zigbee2MQTT:info  2020-10-29 21:49:59: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'system_mode' to 'KA Thermostaat' failed: 'Error: Write 0x00158d00053d2679/1 hvacThermostat({\"16392\":{\"value\":33,\"type\":34}}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":4151,\"transactionSequenceNumber\":null}) failed (Status 'INVALID_VALUE')'","meta":{"friendly_name":"KA Thermostaat"},"type":"zigbee_publish_error"}'
```

herdsman log:

```
Zigbee2MQTT:debug 2020-10-30 08:57:57: Received MQTT message on 'zigbee2mqtt/KA Thermostaat/set' with data '{"current_heating_setpoint": 20.0}'
Zigbee2MQTT:debug 2020-10-30 08:57:57: Publishing 'set' 'current_heating_setpoint' to 'KA Thermostaat'
  zigbee-herdsman:controller:endpoint Write 0x00158d00053d2679/1 hvacThermostat({"16387":{"value":2000,"type":41}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null}) +15s
  zigbee-herdsman:adapter:zStack:adapter sendZclFrameToEndpointInternal 0x00158d00053d2679:51616/1 (0,0,1) +15s
  zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":51616,"destendpoint":1,"srcendpoint":1,"clusterid":513,"transid":24,"options":0,"radius":30,"len":10,"data":{"type":"Buffer","data":[20,55,16,4,2,3,64,41,208,7]}} +15s
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,20,36,1,160,201,1,1,1,2,24,0,30,10,20,55,16,4,2,3,64,41,208,7,223] +15s
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100] +15s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100 +0ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0} +15s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,24,222] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,24,222] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,24] - 222 +0ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":24} +15s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,28,68,129,0,0,1,2,160,201,1,1,0,75,0,220,50,191,0,0,8,28,55,16,4,4,135,3,64,124,2,27] +190ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,28,68,129,0,0,1,2,160,201,1,1,0,75,0,220,50,191,0,0,8,28,55,16,4,4,135,3,64,124,2,27] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [59] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,28,68,129,0,0,1,2,160,201,1,1,0,75,0,220,50,191,0,0,8,28,55,16,4,4,135,3,64,124,2,27,59] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 28 - 2 - 4 - 129 - [0,0,1,2,160,201,1,1,0,75,0,220,50,191,0,0,8,28,55,16,4,4,135,3,64,124,2,27] - 59 +0ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":513,"srcaddr":51616,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":75,"securityuse":0,"timestamp":12530396,"transseqnumber":0,"len":8,"data":{"type":"Buffer","data":[28,55,16,4,4,135,3,64]}} +192ms
  zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":true,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":4,"manufacturerCode":4151,"commandIdentifier":4},"Payload":[{"status":135,"attrId":16387}]},"address":51616,"endpoint":1,"linkquality":75,"groupID":0}' +15s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +3ms
  zigbee-herdsman:controller:endpoint Write 0x00158d00053d2679/1 hvacThermostat({"16387":{"value":2000,"type":41}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null}) failed (Status 'INVALID_VALUE') +51s
Zigbee2MQTT:error 2020-10-30 08:57:57: Publish 'set' 'current_heating_setpoint' to 'KA Thermostaat' failed: 'Error: Write 0x00158d00053d2679/1 hvacThermostat({"16387":{"value":2000,"type":41}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null}) failed (Status 'INVALID_VALUE')'
Zigbee2MQTT:debug 2020-10-30 08:57:57: Error: Write 0x00158d00053d2679/1 hvacThermostat({"16387":{"value":2000,"type":41}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null}) failed (Status 'INVALID_VALUE')
    at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:173:23)
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:202:26)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58)
Zigbee2MQTT:info  2020-10-30 08:57:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'current_heating_setpoint' to 'KA Thermostaat' failed: 'Error: Write 0x00158d00053d2679/1 hvacThermostat({\"16387\":{\"value\":2000,\"type\":41}}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":4151,\"transactionSequenceNumber\":null}) failed (Status 'INVALID_VALUE')'","meta":{"friendly_name":"KA Thermostaat"},"type":"zigbee_publish_error"}'
```

Seems to be a know issue elsewhere: https://forum.iobroker.net/topic/37659/zigbee-eurotronic-spirit-thermostat-funktioniert-nicht

Any idea what's going wrong?

**Comment by Koenkk** [comment] 2020-10-30 08:04
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/4571

**Closed by Koenkk** 2020-10-30 08:04 UTC

**Comment by heggink** [comment] 2020-10-30 08:07
ah, apologies. missed it.
