### ISSUE TITLE
Incorrect rise of the humidity level

### ISSUE THREAD

**Issue by EXP-Carthage** [Koenkk/zigbee-herdsman-converters#4614] opened 2022-09-05 17:21 UTC
With this [sensor](https://www.moeshouse.com/collections/temperature-humidity-sensor/products/smart-zigbee-temperature-and-humidity-sensor-indoor-hygrometer-thermometer-detector?variant=39950390624337), the humidity reading is incorrect.
For example, if the sensor's screen displays a humidity level of 50%, the information returned is 5%.

``` json
{
  "id": 31,
  "type": "EndDevice",
  "ieeeAddr": "0xa4c13808cdabacde",
  "nwkAddr": 9031,
  "manufId": 4417,
  "manufName": "_TZ3000_ywagc4rj",
  "powerSource": "Battery",
  "modelId": "TS0201",
  "epList": [
    1
  ],
  "endpoints": {
    "1": {
      "profId": 260,
      "epId": 1,
      "devId": 770,
      "inClusterList": [
        1,
        3,
        1026,
        1029,
        57346,
        0
      ],
      "outClusterList": [
        3,
        25,
        10
      ],
      "clusters": {
        "msTemperatureMeasurement": {
          "attributes": {
            "measuredValue": 2508
          }
        },
        "msRelativeHumidity": {
          "attributes": {
            "measuredValue": 511
          }
        },
        "genBasic": {
          "attributes": {
            "65503": "\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0011",
            "65506": 51,
            "65508": 0,
            "65534": 0,
            "modelId": "TS0201",
            "manufacturerName": "_TZ3000_ywagc4rj",
            "powerSource": 3,
            "zclVersion": 3,
            "appVersion": 66,
            "stackVersion": 0,
            "hwVersion": 1,
            "dateCode": ""
          }
        },
        "genPowerCfg": {
          "attributes": {
            "batteryPercentageRemaining": 184,
            "batteryVoltage": 29
          }
        }
      },
      "binds": [],
      "configuredReportings": [],
      "meta": {}
    }
  },
  "appVersion": 66,
  "stackVersion": 0,
  "hwVersion": 1,
  "dateCode": "",
  "zclVersion": 3,
  "interviewCompleted": true,
  "meta": {
    "configured": 126974596
  },
  "lastSeen": 1662396642970,
  "defaultSendRequestWhen": "immediate"
}
```

**Comment by Koenkk** [comment] 2022-09-06 08:16
Could you check if the issue is fixed with the following external converter:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const color = require('zigbee-herdsman-converters/lib/color');
const e = exposes.presets;
const ea = exposes.access;

const fzLocal = {
    TS0201_battery: {
        cluster: 'genPowerCfg',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            // https://github.com/Koenkk/zigbee2mqtt/issues/11470
            if (msg.data.batteryPercentageRemaining == 200 && msg.data.batteryVoltage < 30) return;
            return fz.battery.convert(model, msg, publish, options, meta);
        },
    },
    TS0201_humidity: {
        ...fz.humidity,
        convert: (model, msg, publish, options, meta) => {
            const result = fz.humidity.convert(model, msg, publish, options, meta);
            if (meta.device.manufacturerName === '_TZ3000_ywagc4rj') {
                result.humidity = result.humidity * 10;
            }
            return result;
        },
    },
};

const definition = {
    fingerprint: [{manufacturerName: '_TZ2000_a476raq2'}],
    zigbeeModel: ['TS0201', 'SNTZ003'],
    model: 'TS0201',
    vendor: 'TuYa',
    description: 'Temperature & humidity sensor with display',
    whiteLabel: [{vendor: 'BlitzWolf', model: 'BW-IS4'}],
    fromZigbee: [fzLocal.TS0201_battery, fz.temperature, fzLocal.TS0201_humidity],
    toZigbee: [],
    exposes: [e.battery(), e.temperature(), e.humidity(), e.battery_voltage()],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await endpoint.read('genBasic', ['manufacturerName', 'zclVersion', 'appVersion', 'modelId', 'powerSource', 0xfffe]);
    },
};

module.exports = definition;

```

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by EXP-Carthage** [comment] 2022-09-06 08:32
I was just working on a fix. Unfortunately, the fix you suggested doesn't work. The humidity level remains unchanged

**Comment by Koenkk** [comment] 2022-09-06 08:38
I forgot to mention to you have to wait until a new report comes in

**Comment by Koenkk** [comment] 2022-09-06 08:38
I forgot to mention to you have to wait until a new report comes in

**Comment by EXP-Carthage** [comment] 2022-09-06 08:51
I just got a new report and the information is correct thanks to your fix 👍

**Comment by Koenkk** [comment] 2022-09-06 08:55
Great, pushed the fix!

**Closed by Koenkk** 2022-09-06 08:55 UTC
