### ISSUE TITLE
Working on SYMFONISK button; question about sending unsolicited updates

### ISSUE THREAD

**Issue by insensitiveclod** [Koenkk/zigbee-herdsman-converters#658] opened 2019-10-03 13:27 UTC
Hello

I am working on getting the E1744/Symfonisk Sound Controller working with zigbee2mqtt.
No real surprises; it detects motion left en right, sends a cmdToggle and has a different command for double and triple press; for which I created a fz.e1744_skip procedure already.

It is no surprise that in many ways it's like the Ikea ictcg1 device (the original rotatary-knob device they sold in bundles with the first lamps) except that it is less 'broken' (the ictcg1 sends different cmds for different directions; and again different if it's done fast or slow)..

HOWEVER!
The problem with the E1744 seems to be that it ONLY sends a command when rotation STARTS, and another one when rotation STOPS
All events seem to have the same rate: 195... no matter how fast you rotate or which direction.

For this reason, the 'brightness' (or , in my case, 'volume') setting ONLY UPDATES WHEN YOU STOP ROTATING.

If you rotate slowly, you do get intermittent stop/start commands that you can use to correlate the amount of rotation through duration.

But...if you rotate quick, nothing happens...until you stop rotating.

My thinking is that IKEA solves this by doing something smart in the tradfri gateway: sending 'intermediate' volume-update events to the SONOS by starting a timer once you start moving..

I would like to reproduce that mechanism in my support for the E1744 in Zigbee-sheperd-convertors..

For that reason, my question is: is there a way to have a NON-zigbee event (like a timer) be used to send intermittent mqtt-reports ?

The idea being:
- Recieve rotation-cmd -> send mqtt message + start 200ms timer
- Recieve stop-cmnd -> send mqtt message, check for any running timers, kill them

Timer-command:
- Check interval between rotation-start and now; correlate 'level', send mqtt-message
- Update timer-trigger counter.
- Check if timer has been called 10 times; if so, kill timer, send synthetic mqtt-message saying rotation stopped.

All of the above depends on being able to run non-zigbee-triggered callbacks. Is there support for that ?
Is there a place to look at just how every 'device' is set up in zigbee2mqtt ? I am having trouble trying to grok zigbee2mqtt + zigbee-herdsman + zigbee-sheperd-convertors.. 

I am trying to figure out just where I could neatly add code in zigbee-sheperd-convertors in such a way that it'd allow for the above functionality in some way.

Alternatively, instead of sending 'brightness' mqtt-messages. I could send the raw movement-events to mqtt so that it can be picked up by higher level frameworks such as homeassistant/node-red so that this correlation can be done there.

Thanks !

**Comment by Koenkk** [comment] 2019-10-04 12:12
I don't think IKEA does something special related to this; the remote just send the commands directly to the speaker; rotate start -> keep increasing volume until rotate stop is received.

A way to integrate this would be to start a interval timer sending message through the `publish` method (example: https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L286) and stop this timer once the stop is received. You can save a reference to the timer in the store (like done in the example).

**Comment by insensitiveclod** [comment] 2019-10-04 13:52
Awesome.. I'll be looking at that.
I'm not all too familiar with javascript/node; and the idea of having to find out how to write timer-events was quite daunting. I had been looking through the code, but couldnt find an example where I imagined it might be.
This one is very useful. thanks.

However, in a weird twist: it'd seem that I am not able to get the symfonisk button re-connected to my zigbee2mqtt setup. Resetting it (4x shortpress in 5 secs) and then joining (10secs)..does not produce any data in debug-info of zigbee2mqtt anymore.. The button is right next to the dongle.. A weird weird situation; almost as if it only allows being paired once.

I'll have to see if I can get it to pair with the Tradfri hub ...perhaps it requires a software update.

**Comment by diplix** [comment] 2019-10-08 06:48
@insensitiveclod i was wondering how you got signals from the remote in the first place. i also tried to integrate the SYMFONISK Sound Controller. pairing is fine, but after pairing the remote does not seem to send any signals. this is also what @ebaauw observed here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1898#issuecomment-535090364

> It joins deCONZ's ZigBee network without issues. However, it's only responsive for a very brief period after joining the network, and then goes incommunicado. It won't wake on click, turn, or briefly pressing the reset button.
> 
> After several attempts, bombarding it with Read Attributes commands to keep it awake after joining the network, I managed to bind the client OnOff cluster to a group.  

i tried adding the SYMFONISK Sound Controller to a group, but this attempt alsways times out, after re-pairing and restarting z2m alike.

as for configuration i tried to copy bits from the TRADFRI wireless dimmer (in `zigbee-herdsman-converters/devices.js` — i’m on the dev branch) …
```
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genLevelCtrl', 'genPowerCfg']);
            await configureReporting.batteryPercentageRemaining(endpoint);
        },
```
… but the attemp to configure (and bin the endpoint) was always timed out.

it seems to me that after pairing or joining the remote needs to find a group, or else it will fall asleep endlessly.

**Comment by insensitiveclod** [comment] 2019-10-08 11:46
This is interesting. It mimics the issue that I have had too, but only after the FIRST time that I was able to bind it.
That means: the first time I paired the remote to my zigbeestick, things worked fine, except for it not being recognized, etc. 
After editing devices.js with info, events started coming in nicely, and I was able to get some of it working fine.
However, when I tried to go at it again, the next day, it failed entirely to respond.
Using the 4xbuttonpress to reset it also fails to get it to re-bind or do anything useful.
Another unit that I bought , however, directly fails to produce any events. It was able to pair, but that's it. The second unit was from the 'Bargain Bin' , so it has probably been used before and thus MIGHT exhibit different behaviour because of that.

Since I also have a Tradfri-hub and the Ikea-sonos speaker, I'll attempt to get it to bind to the tradfri-hub tonight and see what it does there. 
Perhaps, even, proper COAP info comes out that I could use.

**Comment by diplix** [comment] 2019-10-09 05:17
had an idea yesterday and suceeded (a bit): i just added „ SYMFONISK Sound Controller“ to the „ TRADFRI wireless dimmer“ device configuration.

`        zigbeeModel: ['TRADFRI wireless dimmer', 'SYMFONISK Sound Controller'],`

with this (after two resets/re-pairings) did the controller not only pair, but also bind the endpoints `genLevelCtrl` and `genPowerCfg`. so the pairing and configuration of the comntroller seems to work just as with the wireless dimmer. after this successful pairing and binding i do receive commands:
```
info  2019-10-09T04:50:56: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe4c99dd', payload '{"linkquality":42,"rate":195,"brightness":34,"action":"rotate_left"}'
debug 2019-10-09T04:50:56: Received Zigbee message from '0xccccccfffe4c99dd', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 0
info  2019-10-09T04:50:56: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe4c99dd', payload '{"linkquality":44,"rate":195,"brightness":34,"action":"rotate_stop"}'
debug 2019-10-09T04:50:56: Received Zigbee message from '0xccccccfffe4c99dd', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 0
info  2019-10-09T04:50:56: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe4c99dd', payload '{"linkquality":42,"rate":195,"brightness":34,"action":"rotate_stop"}'
info  2019-10-09T04:50:56: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe4c99dd', payload '{"linkquality":57,"rate":195,"brightness":16,"action":"rotate_stop"}'
```
```
debug 2019-10-09T04:50:59: Received Zigbee message from '0xccccccfffe4c99dd', type 'commandToggle', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
debug 2019-10-09T04:51:17: Received Zigbee message from '0xccccccfffe4c99dd', type 'commandStep', cluster 'genLevelCtrl', data '{"stepmode":0,"stepsize":1,"transtime":0}' from endpoint 1 with groupID 0
debug 2019-10-09T05:06:40: Received Zigbee message from '0xccccccfffe4c99dd', type 'commandStep', cluster 'genLevelCtrl', data '{"stepmode":1,"stepsize":1,"transtime":0}' from endpoint 1 with groupID 0
```

```
debug 2019-10-09T04:51:28: Received Zigbee message from '0xccccccfffe4c99dd', type 'commandMove', cluster 'genLevelCtrl', data '{"movemode":1,"rate":195}' from endpoint 1 with groupID 0
info  2019-10-09T04:51:28: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe4c99dd', payload '{"linkquality":42,"rate":195,"brightness":16,"action":"rotate_left"}'
debug 2019-10-09T04:51:28: Received Zigbee message from '0xccccccfffe4c99dd', type 'commandMove', cluster 'genLevelCtrl', data '{"movemode":1,"rate":195}' from endpoint 1 with groupID 0
info  2019-10-09T04:51:28: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe4c99dd', payload '{"linkquality":42,"rate":195,"brightness":16,"action":"rotate_left"}'
info  2019-10-09T04:51:28: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe4c99dd', payload '{"linkquality":57,"rate":195,"brightness":9,"action":"rotate_left"}'
debug 2019-10-09T04:51:28: Received Zigbee message from '0xccccccfffe4c99dd', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 0
info  2019-10-09T04:51:28: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe4c99dd', payload '{"linkquality":42,"rate":195,"brightness":9,"action":"rotate_stop"}'
debug 2019-10-09T04:51:29: Received Zigbee message from '0xccccccfffe4c99dd', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 0
info  2019-10-09T04:51:29: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe4c99dd', payload '{"linkquality":39,"rate":195,"brightness":9,"action":"rotate_stop"}'
debug 2019-10-09T04:51:29: Received Zigbee message from '0xccccccfffe4c99dd', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 0
info  2019-10-09T04:51:29: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe4c99dd', payload '{"linkquality":39,"rate":195,"brightness":9,"action":"rotate_stop"}'
info  2019-10-09T04:51:29: MQTT publish: topic 'zigbee2mqtt/0xccccccfffe4c99dd', payload '{"linkquality":57,"rate":195,"brightness":9,"action":"rotate_stop"}'
```

brightness values after `commandMove` and action `rotate_left` or `rotate_right` are reported from 0-250. single click is `commandToggle`, double click is `commandStep` with `stepmode` 1, triple click is `commandStep` with `stepmode` 2.

so whats missing for the controller is not only the device configuration, but also some kind of onboarding that is configured for the other tradfri buttons and dimmers. maybe @Koenkk can step in and point to the right direction.

**Comment by diplix** [comment] 2019-10-10 07:13
after successful pairing i successfully used this setup in `devices.js` (dev branch):
```
    {
        zigbeeModel: ['SYMFONISK Sound Controller'], 
        model: 'E1744', 
        vendor: 'IKEA', 
        description: 'SYMFONISK Sound Controller ', 
        supports: 'turn, click', 
        fromZigbee: [
            fz.cmdToggle, fz.E1744_clicks, fz.cmd_move, fz.cmd_move_with_onoff, fz.cmd_stop, fz.cmd_stop_with_onoff,
            fz.cmd_move_to_level_with_onoff, fz.generic_battery,
        ],
        toZigbee: [],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genLevelCtrl', 'genPowerCfg']);
            await configureReporting.batteryPercentageRemaining(endpoint);
        },
    },
```
with this added to `fromZigbee.js`
```
    E1744_clicks: {
        cluster: 'genLevelCtrl',
        type: 'commandStep',
        convert: (model, msg, publish, options) => {
            const deviceID = msg.device.ieeeAddr;
            const direction = msg.data.stepmode === 1 ? 'triple' : 'double';

            return {
                action: `${direction}_click`,
                step_size: msg.data.stepsize,
                transition_time: msg.data.transtime,
            };
        },
    },
```
`fz.cmd_move_with_onoff` and `fz.cmd_stop_with_onoff` are probably not needed (device sends no off) and the turning rate that `const ictcg1` calculates is always a constant 195:
`info  2019-10-10T07:10:13: MQTT publish: topic 'zigbee2mqtt/symfonisk_sound_controller', payload '{"linkquality":63,"rate":195,"brightness":210,"battery":74,"action":"rotate_stop"}'`
overall the turning speed does not seem to correspond to thhe values that z2m outputs. it works, but the speed seems too low.

**Comment by baurmatt** [comment] 2019-10-13 17:09
Also interested in having support for the Symfonisk button! :) If you need help, let me know. Don't have Javascript experience but the button is already laying on my table.

**Comment by diplix** [comment] 2019-10-14 06:08
i have a question: i bound (binded) my symfonisk controller successfully to three radfri spots (that are paired to z2m). i can flawlessly change brightness with the controller and also the toggle (one click) action works (sort of): it toggles twice. also the z2m debug logs show, that upon a single click two toggle events are fired. since i deny my tradfri gateways internet access (to keep an older, working setup) i can’t update the symfonisk controllers frmware.

i was wondering if someone could check if teh symfonisk controller still issue a double toggle upon clicking it once (should be overservable in the debug logs if successfull ypaired to z2m).

**Comment by baurmatt** [comment] 2019-10-19 11:57
This is really strange... Tried to connect my Symfonisk button with zigbee2mqtt but it just won't join the network. Tried resetting/rejoining it multiple times, just doesn't work.

On the other hand, I might use it as a remote for my Osram Smart Plug... It magically turns on/off if I press the Symfonisk button. This is also reproducible if I turn off all my Zigbee routers (Hue Bridge/Raspberry Pi running zigbee2mqtt). I have no idea how this is technical possible, but it happens...

**Comment by Imperial-Guard** [comment] 2019-10-26 09:14
Got the following error with the latest dev:

`zigbee2mqtt:error 2019-10-26T09:13:56: Failed to configure 'living_room/sensor/0008/symfonisk', attempt 2 (Error: AREQ - ZDO - bindRsp after 10000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10))
`

**Comment by Koenkk** [comment] 2019-10-26 10:11
I will close this as the device is supported now. Thanks all!

**Closed by Koenkk** 2019-10-26 10:11 UTC

**Comment by baurmatt** [comment] 2019-10-26 10:34
(Add cross reference #711)

**Comment by GMFalka** [comment] 2019-12-09 21:34
Sorry for reopening this.

Bought, paired, using one of these new remotes for my lights. 

Can zigbee2mqtt change how binded devices interact with eachother? I presume it can't. :/

If binded to a light, the new symfonisk remote cannot turn on or off a light with a turning motion.
If binded to a light, the symfonisk remote 1 button press action just flashes the light for 1 sec.

**Comment by phoxy84** [comment] 2019-12-30 17:36
I bought a E1744 and paired with z2m. After that, nothing happens. Clicks and rotations don’t show up in the logs. Any advise?

**Comment by xaviml** [comment] 2020-01-05 10:55
Same problem as phoxy84 over here.

**Comment by thrawnarn** [comment] 2020-01-07 17:50
I have the same problem :(

**Comment by phoxy84** [comment] 2020-01-26 19:43
Here are my logs:

`zigbee2mqtt:info  2020-01-26 20:35:57: Successfully interviewed '0x14b457fffe79913e', device has successfully been paired
zigbee2mqtt:info  2020-01-26 20:35:57: Device '0x14b457fffe79913e' is supported, identified as: IKEA SYMFONISK sound controller (E1744)
zigbee2mqtt:info  2020-01-26 20:35:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x14b457fffe79913e","model":"E1744","vendor":"IKEA","description":"SYMFONISK sound controller","supported":true}}'
zigbee2mqtt:info  2020-01-26 20:35:57: Configuring '0x14b457fffe79913e'
zigbee2mqtt:info  2020-01-26 20:36:01: Successfully configured '0x14b457fffe79913e' `

No result when turning or clicking the button.

**Comment by phoxy84** [comment] 2020-02-19 08:47
I updated the E1744 firmware (with the new [OTA functionality](https://github.com/Koenkk/zigbee2mqtt/issues/2921#issuecomment-586684799)) and now it seems to work. I was on firmware 2.1.022.
