### ISSUE TITLE
Aqara Smart Plug EU [SP-EUC01] - All exposed sensors (beside power) show null

### ISSUE THREAD

**Issue by fluffymadness** [Koenkk/zigbee-herdsman-converters#2908] opened 2021-08-14 12:16 UTC
Model: lumi.plug.maeu01, SP-EUC01
Zigbee2mqtt:  1.21.0-1

This seems to be some kind of regression, since this has worked fine in older zigbee2mqtt versions.
Only value that randomly seems to work is power. Everything else just gives nothing.
```
{
    "linkquality": 72,
    "power": 11.2,
    "state": "ON",
    "update": {
        "state": "idle"
    },
    "update_available": false,
    "current": null,
    "energy": null,
    "temperature": null,
    "voltage": null
}
```

**Comment by Koenkk** [comment] 2021-08-15 18:25
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/6861

**Closed by Koenkk** 2021-08-15 18:25 UTC
