### ISSUE TITLE
Add Xiaomi Aqara D1 switch QBKG26LM decoupled mode 

### ISSUE THREAD

**Issue by chankalson** [Koenkk/zigbee-herdsman-converters#1986] opened 2020-12-28 08:44 UTC
The Aqara D1 switch QBKG26LM is a 3-gang switch (with Neutral wire), however decoupled mode is not available even though the same 3-gang QBKG25LM (no neutral) has it.

ERROR: No converter available for 'operation_mode' ([object Object])

**Comment by Koenkk** [comment] 2020-12-28 12:41
First step would be to sniff the traffic with the original xiaomi gateway to figure out what to send. https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html .

Next add `tz.xiaomi_switch_operation_mode` to the `toZigbee` array of the QBKG26LM in devices.js and modify https://github.com/Koenkk/zigbee-herdsman-converters/blob/b441c7e3a2c040594e62c504c6466db0e904bd96/converters/toZigbee.js#L1436 accordingly (to what you sniffed)

**Comment by chankalson** [comment] 2020-12-28 13:02
Thanks for the response.

I'm using the Zigbee2mqtt add-on in Home Assistant. May I know where is the toZigbee.js file located?

Thanks again.

**Comment by Koenkk** [comment] 2020-12-28 13:08
For the addon it's a bit more complicated. SSH into the machine, figure out the container ID with `docker ps -a`, ssh into with `docker exec -it [CONTAINER_ID] sh`. The `toZigbee.js` should be under `node_modules/zigbee-herdsman-converters/converters/toZigbee.js`.

**Comment by chankalson** [comment] 2021-01-05 05:58
Hi @Koenkk , Happy New Year to you!

I've captured the traffic from the QBKG26LM to Aqara Hub. 
[QBKG26LM.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/5768381/QBKG26LM.zip)

I pressed each button on the QBKG26LM twice, thus turning it ON->OFF starting from left to right. After that I turned on the Wireless Switch function for all 3 buttons from the Mi Home app, and pressed each button once, from left to right.

May I know what do I need to modify in devices.js and toZigbee.js?

Thanks a lot for your help.

**Comment by Koenkk** [comment] 2021-01-05 18:09
@chankalson I need a sniff off setting the decoupled mode from the Xiaomi gateway (keep the sniff as short as possible, so start sniffing right before you change the decoupled mode). Also share your network key

**Comment by chankalson** [comment] 2021-01-05 18:27
@Koenkk, here's the new sniff file 
[QBKG26LM Decoupled.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/5771902/QBKG26LM.Decoupled.zip)

I've set decoupled mode for the 3 buttons. My network encryption key is 404546133c11a2bff89dbe2b74e99a57.

Thanks again! Let me know if you need anything else.

**Comment by Koenkk** [comment] 2021-01-05 19:13
Added. docs: https://www.zigbee2mqtt.io/devices/QBKG25LM.html#decoupled-mode (use the one of QBKG25LM).

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by chankalson** [comment] 2021-01-05 19:35
@Koenkk, I've edited my toZigbee.js file to match your commit, and added this line "toZigbee: [tz.xiaomi_switch_operation_mode]," to QBKG26LM in devices.js. However, there is no action property appaearing for the device.

**Comment by chankalson** [comment] 2021-01-06 03:32
Hi @Koenkk, the decoupled mode works (the button does not control the relay). However, there isn’t any action value/property for the switch. Is there anything else i need to modify?

**Comment by Koenkk** [comment] 2021-01-06 17:39
Did some more fixes, try again with latest dev.

**Comment by chankalson** [comment] 2021-01-07 04:06
@Koenkk I'm on the latest dev commit: 4c95265, but still seems the same, nothing is transmitted when i press the decoupled button.

**Comment by Koenkk** [comment] 2021-01-07 18:14
Ah, `action` was indeed not added yet. Added now.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by chankalson** [comment] 2021-01-09 06:25
@Koenkk The action property shows up in the 'exposes' tab in front end now, but still no action is received when decoupled button is pressed.

**Comment by chankalson** [comment] 2021-01-09 06:39
@Koenkk There's a typo of the switch model under 'xiaomi_multistate_action' in fromZigbee.js. Should be QBKG26LM, not QKBG26LM. No wonder it's still not working. 🤣

**Comment by Koenkk** [comment] 2021-01-09 13:06
ah fixed now

**Comment by chankalson** [comment] 2021-01-10 03:47
@Koenkk Still no actions being sent from the switch on latest dev, any idea why?

**Comment by Koenkk** [comment] 2021-01-10 14:32
Can you provide the debug log when clicking the bug?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by chankalson** [comment] 2021-01-10 14:55
This is the log when decoupled mode is not enabled for the button:
`Zigbee2MQTT:debug 2021-01-10 22:53:55: Received Zigbee message from 'Room 3 Switch', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 2 with groupID 0
Zigbee2MQTT:info  2021-01-10 22:53:55: MQTT publish: topic 'zigbee2mqtt/Room 3 Switch', payload '{"linkquality":44,"operation_mode":"decoupled","state_center":"ON","state_left":"ON","state_right":"OFF"}'`

There is nothing logged when the decoupled button is clicked.

**Comment by Koenkk** [comment] 2021-01-10 16:22
- Are you sure the QBKG26ML is in decoupled mode? The message looks entirely different than what the QBKG26LM uses.
- If yes, can you provide me the debug logs when doing a, click, release and hold in both decoupled and non-decoupled mode. In the log add comments before each `Received Zigbee message` with what actions it was triggered (click,release,hold)

**Comment by chankalson** [comment] 2021-01-10 16:44
Yes, i'm sure the button is in decoupled mode because when i click it does not turn on/off the relay. 

In **decoupled mode**, there is no `Received Zigbee message`, no matter click, release or hold, nothing happens in the log, which is what i find strange. I've tried re-pairing the switch, and also tried with another switch of same model. 

In **non-decoupled mode**, this is the only `Received Zigbee message`, no matter click, release or hold:
`Received Zigbee message from 'Room 3 Switch', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 2 with groupID 0` _(Turn on relay)_
`Received Zigbee message from 'Room 3 Switch', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 2 with groupID 0` _(Turn off relay)_

**Comment by Koenkk** [comment] 2021-01-10 16:48
> In decoupled mode, there is no Received Zigbee message, no matter click, release or hold, nothing happens in the log, which is what i find strange. I've tried re-pairing the switch, and also tried with another switch of same model.

That explains a lot. Can you sniff the traffic when clicking the button in decoupled mode, do you see any messages being send directly after pressing the button? If not, can you try sniffing the same but then with the Xiaomi gateway?

**Comment by chankalson** [comment] 2021-01-10 17:06
![image](https://user-images.githubusercontent.com/15264510/104129898-35ac6100-53a9-11eb-95da-ea904d4e0b2f.png)
This was sent after pressing the button.

**Comment by chankalson** [comment] 2021-01-10 17:20
![image](https://user-images.githubusercontent.com/15264510/104130328-0860b280-53ab-11eb-8221-5eb607e633f4.png)

This is sniffed from the Xiaomi Gateway with a button click in decoupled mode.

**Comment by Koenkk** [comment] 2021-01-10 18:21
That's indeed exactly what I would expect: https://github.com/Koenkk/zigbee-herdsman-converters/issues/1986#issuecomment-757511288

Did you enable the decoupled mode for each endpoint (left,center,right)? In your Xiaomi gateway sniff I see the gateway does this.

**Comment by chankalson** [comment] 2021-01-10 18:31
Yes I tried enabling decoupled mode for all 3 endpoints, still the same.

This is the debug log when i enable the decoupled mode:
`Received MQTT message on 'zigbee2mqtt/Living Room Switch 1/right/set' with data '{ "operation_mode": { "state": "decoupled" } }'
Publishing 'set' 'operation_mode' to 'Living Room Switch 1'
Received Zigbee message from 'Living Room Switch 1', type 'attributeReport', cluster 'aqaraOpple', data '{"512":0}' from endpoint 3 with groupID 0`

**Comment by Koenkk** [comment] 2021-01-10 18:47
Can you provide the log when pairing the QBKG26LM with the xiaomi gateway? Once it's paired click the button once so I can see the click message.

**Comment by chankalson** [comment] 2021-01-10 19:03
Here's the sniff of pairing the switch and left button click:
[QBKG24LM SNIFF.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/5793159/QBKG24LM.SNIFF.zip)

The button click is on Frame 70, Multistate Input on Frame 72.

**Comment by Koenkk** [comment] 2021-01-10 19:48
Looks it does nothing special. Can you try removing line https://github.com/Koenkk/zigbee-herdsman-converters/blob/dc91a73ae7cddf53733eed2ef0369a7a7cc71a72/devices.js#L576 till https://github.com/Koenkk/zigbee-herdsman-converters/blob/dc91a73ae7cddf53733eed2ef0369a7a7cc71a72/devices.js#L583 and pair with z2m again. Does it work after this?

**Comment by chankalson** [comment] 2021-01-11 00:06
Nope, still doesn't work unfortunately.

**Comment by chankalson** [comment] 2021-01-11 01:34
Nope, still doesn't work unfortunately.

Could it be that we have to poll the switch for the Multistate Input?

Or is it possible that the QBKG26LM is able to recognise the Xiaomi gateway and only send certain messages there?
Or could it be related to zStack version?

**Comment by Koenkk** [comment] 2021-01-11 16:17
Can you try changing it to:

```js
        configure: async (device, coordinatorEndpoint, logger) => {
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff', 'genMultistateInput']);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff', 'genMultistateInput']);
            await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff', 'genMultistateInput']);
            await reporting.onOff(device.getEndpoint(1));
            await reporting.onOff(device.getEndpoint(2));
            await reporting.onOff(device.getEndpoint(3));
        },
```

and reconfigure the switch via: https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgerequestdeviceconfigure

If that doesn't help; 
- the snif you provided in https://github.com/Koenkk/zigbee-herdsman-converters/issues/1986#issuecomment-757526504 doesn't contain any commands to put the switch into decoupled mode. Was the switch already in decoupled mode when joining? If yes, provide a sniff when joining as not decoupled, decouple it and press the buttons
- when taking the z2m sniffs, do you sniff really close to the QBKG26LM? In this way we know for sure that the QBKG26LM is not sending the messages (otherwise it could be that some router refuses to forward this message)

**Comment by chankalson** [comment] 2021-01-11 17:01
Hi @Koenkk,

- I've tried changing the code but it still does not work.

- The sniff i provided in #1986 (comment) was in non-decoupled mode. I've done a new sniff here [Xiaomi Gateway Sniff QBKG26LM.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/5797156/Xiaomi.Gateway.Sniff.QBKG26LM.zip). 

I'm sorry the sniff is quite long, i've noted the frames of each action as below:
**Non-decoupled mode:**
Frame 84, 88 - Left button turn On and Off
Frame 96, 100 - Center button turn On and Off
Frame 106, 110 - Right button turn On and Off

**Decoupling the buttons:**
Frame 148 - Decouple Left button
Frame 180 - Decouple Center button
Frame 194 - Decouple Right button

**Decoupled mode:**
Frame 210 - Left button click
Frame 212 - Center button click
Frame 216 - Right button click

- I've tried taking the z2m sniff standing next to the switch, nothing is sent in decoupled mode.

**Comment by Koenkk** [comment] 2021-01-11 17:10
TBH I'm running out of ideas here, I don't see any setup done for the multistateInput messages. As last resort, can you make the same sniff with Z2M so I can do a detailed comparison)

**Comment by chankalson** [comment] 2021-01-11 17:27
Same here, really can't figure out what's the problem.

Here's the sniff with Z2M [Z2M Sniff QBKG26LM.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/5797334/Z2M.Sniff.QBKG26LM.zip).

First, joined the device to Z2M, then
**Non-decoupled mode:**
Frame 297, 304 - Left button turn On and Off
Frame 385, 393 - Center button turn On and Off
Frame 419, 423 - Right button turn On and Off

**Decoupling the buttons:**
Frame 482 - Decouple Left button
Frame 566 - Decouple Center button
Frame 585 - Decouple Right button

**Decoupled mode:**
I clicked the 3 buttons, but I don't see any messages sent except for 3 Link Status from the switch at Frame 603, 618, 644.

**Comment by Koenkk** [comment] 2021-01-11 18:27
I cannot find why it's not working. Strange thing that it goes into decoupled mode but doesn't send any actions. I noticed that the Xiaomi gateway always sends the write attributes twice so maybe you can also try that. In order: 2x left, 2x center, 2x right

**Comment by chankalson** [comment] 2021-01-12 14:32
Doesn't work.. I shall give up and change the switch to the QBKG25LM instead 🙄
But thank you so much for all the help, really appreciate it.

On a side note, can you help to add the decoupled mode and action exposes for the QBKG23LM? (Should be same as the QBKG11LM)
This one does send the MultistateInput because there's this message:
`No converter available for 'QBKG23LM' with cluster 'genMultistateInput' and type 'attributeReport' and data '{"presentValue":1}'`

Here's the sniff of enabling decoupled mode and single click:
[QBKG23LM.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/5802693/QBKG23LM.zip)
Enabling decoupled on frame 2, Button click on Frame 29.

**Comment by Koenkk** [comment] 2021-01-12 20:06
No problem, added

**Comment by chankalson** [comment] 2021-01-13 00:49
Works perfect, thanks!

**Comment by Koenkk** [comment] 2021-01-13 18:00
Cool, I assume this can be closed now.

**Comment by slydiman** [comment] 2021-02-08 23:46
> I cannot find why it's not working. Strange thing that it goes into decoupled mode but doesn't send any actions. I noticed that the Xiaomi gateway always sends the write attributes twice so maybe you can also try that. In order: 2x left, 2x center, 2x right

The action still does not work on QBKG26LM with z2m!
QBKG26LM sends Report Attributes on button pressing from endpoints 41 (left button), 42 (center) and 43 (right) immediately after peering with Xiaomi Gateway 2. It does not depend on the decoupled mode at all.

The decoupled mode is absolutely useless on QBKG26LM without actions.

Here is the sniff of MiHome peering and clicking left, center, right:
http://slydiman.me/_t/qbkg26lm/peering_mihome_test2_click_left_center_right.pcapng
ZigBee keys:
5A:69:67:42:65:65:41:6C:6C:69:61:6E:63:65:30:39
60e566b35cb1c25f183ddecb9489baf7

**Comment by Koenkk** [comment] 2021-02-09 11:15
@slydiman thanks for your sniff but I still cannot spot the crucial difference here. All looks pretty standard.

**Comment by slydiman** [comment] 2021-02-09 14:51
Let's investigate together. 
How can I help? 

Here is my repro steps:
- Pair with z2m. 
- States on/off work fine. BTW, I don't see power/load and energy/consumption. Currently at least SLS supports the power for QBKG26LM.
- There is no action. Shiff shows no any reports from endpoints 41, 42, 43.
- Pair with Xiaomi Gateway 2. Shiff shows that pair process is very short and simply. And sniff shows reports from endpoints 41, 42, 43 immediately after pairing.

I see the following strange behavior:
- QBKG26LM did not response to read Application ver(1).
- QBKG26LM requests the time and time zone.

In case of z2m QBKG26LM does not request the time and time zone.
Currently I have no idea what is the magic flag/request/sequence which disables action reports from endpoints 41, 42, 43.

I tried to power off/on QBKG26LM after pairing - nothing changed. 
Something important was saved/configured during the pairing process.

**Comment by Koenkk** [comment] 2021-02-09 16:14
Appreciate your efforts but since I already put too much time into this issue and I don't see anything different in your sniffs I don't want to continue further on it.

**Comment by slydiman** [comment] 2021-02-10 19:49
Probably I have figured out the root of problem.

Here is the pairing process with Xiaomi Gateway 2:
```
0000 > Broadcast: Permit Join Request
QBKG26LM > 0000 Association Request - get network address A4DD
0000 > A4DD Transport Key
A4DD > Broadcast: Device Announcement
0000 > A4DD: Read Attributes: Model (5)
A4DD > 0000: Response Model lumi.switch.n3acn3
0000 > A4DD: Read Attributes: App Ver (1)
!!! No App Ver read attribute response !!!
A4DD > 0000: Node Descriptor Request
0000 > A4DD: Node Descriptor Response
The coordinator's Node Descriptor Response content is very important:
    Capability Information: 0x8f
    Manufacturer Code: 0x115f
    Max Buffer Size: 127
    Max Incoming Transfer Size: 0
    Server Flags: 0x0041
    Max Outgoing Transfer Size: 0
    Descriptor Capability Field: 0x00

A4DD > 0000: Report Attributes:  Manufacturer specific (0xfcc0) attribute (0xf7) [bytes]
A4DD > 0000: Report Attributes:  Basic: model (5) lumi.switch.n3acn3

A4DD > 0000: Read attribute: time, time zone < This is a good sign!!!
...
```

Here is the pairing process with a custom gateway using the coordinator on CC2538:
```
QBKG26LM > 0000 Association Request - get network address 1307
0000 > 1307 Transport Key
1307 > Broadcast: Device Announcement
1307 > 0000: Node Descriptor Request
!!! 0000 Ignore  Node Descriptor Request !!!
0000 > 1307: Read Attributes: Model (5)
1307 > 0000: Response Model lumi.switch.n3acn3
0000 > 1307: Read Attributes: App Ver (1)
1307 > 0000: Response App Ver 0x20

0000 > 1307: Node Descriptor Request
1307 > 0000: QBKG26LM Node Descriptor Response:
    Capability Information: 0x8e
    Manufacturer Code: 0x115f
    Max Buffer Size: 127
    Max Incoming Transfer Size: 100
    Server Flags: 0x2c00
        0010 110. .... .... = Stack Compliance Revision: 22
    Max Outgoing Transfer Size: 100
    Descriptor Capability Field: 0x00

1307 > 0000: Node Descriptor Request
0000 > 1307: Node Descriptor Response
The coordinator's Node Descriptor:
    Capability Information: 0x8f
    Manufacturer Code: 0x0000
    Max Buffer Size: 80
    Max Incoming Transfer Size: 160
    Server Flags: 0x0001
    Max Outgoing Transfer Size: 160
    Descriptor Capability Field: 0x00

Immediately after that:
1307 > Broadcast: Permit Join Request
That means "give me another gateway!"
```
It is possible to pair QBKG26LM after few tries. 
But QBKG26LM did not request time and do not report action (from endpoints 41, 42, 43).

Is it possible to customize the coordinator's Node Descriptor to simulate the manufacturer code 0x115f at least for QBKG26LM?
Most probably Xiaomi/Aqara disabled some functionality for other gateways. Еhis is a bad trend.

**Comment by Koenkk** [comment] 2021-02-11 18:42
@Hacker-CB can you try changing the manufacturer code to 0x115F to test if this indeed the reason? I believe it can be changed in `zd_config.c` 

![image](https://user-images.githubusercontent.com/2892853/107682966-50703f00-6ca1-11eb-938e-b04a80bbcb10.png)

**Comment by Hacker-CB** [comment] 2021-02-11 18:48
@0x3EC ?

**Comment by slydiman** [comment] 2021-02-12 02:10
BTW, why Server Flags is 0x0001 in the coordinator's Node Descriptor?
The bit 0x40 means Network Manager = true.
Xiaomi Gateway 2 reports Server Flags 0x0041.
Tuya gateway reports Server Flags 0x2c41 (where 0x2cxx means Stack Compliance Revision 22).

**Comment by 0x3EC** [comment] 2021-02-12 17:37
[JH_2538_2592_ZNP_USB_20210212_115F.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/5973448/JH_2538_2592_ZNP_USB_20210212_115F.zip)

@Koenkk, that's right. the code is set here
```
ZDO_Config_Node_Descriptor.ManufacturerCode[0] = 0x5F;
ZDO_Config_Node_Descriptor.ManufacturerCode[1] = 0x11;
```

**Comment by slydiman** [comment] 2021-02-13 20:05
> [JH_2538_2592_ZNP_USB_20210212_115F.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/5973448/JH_2538_2592_ZNP_USB_20210212_115F.zip)

Excellent! I can confirm that the action topic exists and works just fine for QBKG26LM!
I see the following actions: single_left, single_center, single_right, double_left, double_center, double_right.
The same in the decoupled mode.

I see the following endpoints and clusters: 1, 2, 3, 21 (genAnalogInput), 31 (genAnalogInput), 41 (genMultistateInput), 42 (genMultistateInput), 43 (genMultistateInput), 51 (genMultistateInput), 52 (genMultistateInput), 53 (genMultistateInput), 61 (genMultistateInput), 242 (output greenPower).

Note endpoints 1, 2, 3 contain the following clusters in Z2M: genBasic, genIdentify, genGroups, genScenes, genOnOff, genMultistateInput, aqaraOpple. 
But endpoints 1, 2, 3 contain the following clusters in SLS gateway: GEN_BASIC, GEN_DEVICE_TEMP_CONFIG, GEN_IDENTIFY, GEN_GROUPS, GEN_SCENES, GEN_ON_OFF, GEN_ALARMS, SE_SIMPLE_METERING, HA_ELECTRICAL_MEASUREMENT.
No idea why they are different. 
Anyway I don't see power/load and energy/consumption topics in Z2M.
Probably is is necessary to request these values periodically.

@0x3EC, could you provide the UART version of the same firmware too, please?
Thanks in advance!

**Comment by 0x3EC** [comment] 2021-02-14 18:35
[JH_2538_2592_ZNP_UART_20210212_115F.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/5978250/JH_2538_2592_ZNP_UART_20210212_115F.zip)

**Comment by slydiman** [comment] 2021-02-18 12:46
Has anyone plans to update the coordinator's firmware API to customize the manufacturer code?

**Comment by lovelylain** [comment] 2021-02-23 02:21
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/toZigbee.js#L1700
await entity.read('aqaraOpple', <del>0x0200</del>[0x0200], manufacturerOptions.xiaomi);

**Comment by lovelylain** [comment] 2021-02-23 02:37
@slydiman power consumption can by solved by bind.

**Comment by AbysFlo** [comment] 2021-03-05 14:49
Hello, I'm facing this same issue with the QBKG25LM. If I can help in any way to find a solution.

**Comment by redesigndavid** [comment] 2021-04-29 09:38
Any kind soul want to add updated firmwares to Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/default?  I tried using the firmware 0x3EC posted, but I'm guessing it's not the home 1.2 version.

**Comment by Koenkk** [comment] 2021-05-05 18:08
good that https://github.com/Koenkk/zigbee-herdsman-converters/issues/1986#issuecomment-778337754 fixes this, the problem I'm having this is that we don't want to do this for all devices, only for this one. @0x3EC do you see any possibility to do this?

**Comment by re-engr** [comment] 2021-05-06 14:16
> good that [#1986 (comment)](https://github.com/Koenkk/zigbee-herdsman-converters/issues/1986#issuecomment-778337754) fixes this, the problem I'm having this is that we don't want to do this for all devices, only for this one. @0x3EC do you see any possibility to do this?

Need to change ManufacturerCode in Z-Stack_Home_1.2 firmware?

**Comment by 0x3EC** [comment] 2021-05-06 14:18
> good that [#1986 (comment)](https://github.com/Koenkk/zigbee-herdsman-converters/issues/1986#issuecomment-778337754) fixes this, the problem I'm having this is that we don't want to do this for all devices, only for this one. @0x3EC do you see any possibility to do this?

Need to change ManufacturerCode in Z-Stack_Home_1.2 firmware?

**Comment by Koenkk** [comment] 2021-05-06 16:18
No, I mean if it can be enabled only for the connection with the QBKG26LM, since this may break e.g. Hue devices.

**Comment by redesigndavid** [comment] 2021-05-11 01:06
+1 

I'm guessing the Z-Stack_Home_1.2 firmware has it's own manufacturer code and we've switched it in the past to match what hue devices would expect?

**Comment by sunsamzhen** [comment] 2021-06-14 11:15
It may be the QBKG26LM 02-24-2020 firmware issue，something changed  in this version.
I try to add `await device.getEndpoint(1).write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f});` in
```ruby
 configure: async (device, coordinatorEndpoint, logger) => {
            await device.getEndpoint(1).write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f});
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(device.getEndpoint(1));
            await reporting.onOff(device.getEndpoint(2));
            await reporting.onOff(device.getEndpoint(3));
        }
```
and re-pairing the switch, then do some actions, the action info come out.

![截屏2021-06-14 下午6 51 07](https://user-images.githubusercontent.com/4156264/121881360-c238c200-cd41-11eb-810e-2a093a19c0b6.png)

### It work!!!

it can recognize 'hold',  'single',  'double' and 'triple' actions, but need to rewrite converter to support  'hold' and 'triple'.

**Comment by satedone** [comment] 2021-06-17 17:10
Please tell me in simple terms, what should I do to make my actions work on this switch? I did QBKG26LM decoupled mode but can't see actions.

**Comment by redesigndavid** [comment] 2021-06-17 21:30
I tried to do this last night too.  This is what I did:
1. Fresh image of raspberry pi
2. Installed zigbee2mqtt
3. Ran it first, updated the configuration, exited the process
4. Open "node_modules/zigbee-herdsman-converters/devices/xiaomi.js" and added that "await device.getEndpoint(1).write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f});" on line 429.
5. Started the process. Repaired the QBKG26LM. Sent the decoupled command.  I do this via: 
```mosquitto_pub -t 'zigbee2mqtt/0x54ef4410000177c0/set' -m '{"operation_mode_right": "decoupled"}'```
6. I see logs saying my switch is decoupled, and it's definitely decoupled.  But nothing in the logs when I press the right button like yours.

@sunsamzhen how do you activate your 'decoupled' mode? Looking at the steps I followed outlined above, do you think I'm missing anything?  Thank you!

**Comment by redesigndavid** [comment] 2021-06-17 23:37
Scratch that.  I got it to work.  I looked at my switches initialization and turns out I have a QBKG25LM.  I added that same line for that device it worked as well! BRAVO!

**Comment by redesigndavid** [comment] 2021-06-20 08:38
@Koenkk is it possible to include this update?

**Comment by Koenkk** [comment] 2021-06-20 18:46
@redesigndavid when adding `await device.getEndpoint(1).write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f});` does it still report state changes when not in decoupled mode?

**Comment by lovelylain** [comment] 2021-06-21 05:00
@Koenkk mode 1 will make QBKG26LM behave like QBKG24LM and other old models, it report state changes whether it's decoupled mode or not, `fz.xiaomi_power` can be added for power measure. It is suggested that replace `fz.xiaomi_multistate_action` with `fz.aqara_opple_multistate`, because the code of the `fz.xiaomi_multistate_action` is ugly and cannot cover all combinations, the `fz.aqara_opple_multistate` is more general.
```
button_41: left
button_42: center
button_43: right
button_51: left&center
button_52: left&right
button_53: center&right
button_61: left&center&right
every button has single and double event.
```

**Comment by Koenkk** [comment] 2021-06-21 08:19
@lovelylain could you make a pull request with these changes?

>  because the code of the fz.xiaomi_multistate_action is ugly and cannot cover all combinations, the fz.aqara_opple_multistate is more general.

But does this change the published values for `action`? If yes, this is a breaking change and I propose to update `fz.xiaomi_multistate_action` instead to cover the missing combinations.

**Comment by balonchiks** [comment] 2021-06-23 11:43
> 
> 
> @redesigndavid when adding `await device.getEndpoint(1).write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f});` does it still report state changes when not in decoupled mode?

came here [from here](https://github.com/Koenkk/zigbee2mqtt/issues/5106), and I can confirm that adding this line (i am using QBKG25LM) - the state changes is also reported when the switch **_is not_** in the decoupled mode.

as with other people in this thread - without this line in xiaomi.js (and firmware from [this post](https://github.com/Koenkk/zigbee-herdsman-converters/issues/1986#issuecomment-778337754)) - QBKG25LM does not report anything when in decoupled mode

**Comment by Koenkk** [comment] 2021-06-26 15:09
@redesigndavid @balonchiks thanks for confirming, added the fix. 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by redesigndavid** [comment] 2021-06-27 05:19
Huge thanks @Koenkk !  Looks as though you applied it to QBKG25LM, but not QBKG26LM.  I only have a QBKG26LM and the fix works for that too.  Hope you could also apply to QBKG26LM, thank you so much!  Quite excited to try it out.

**Comment by skyksandr** [comment] 2021-06-27 17:14
First of all, Thank you @Koenkk for your work!
Came here from google as I have exact same issue. Switched to dev branch, re-paired device, but no luck, not getting an event. 
Let me know if I can help somehow

**Comment by ruifung** [comment] 2021-06-28 06:27
As stated by @sunsamzhen above, I needed to add 
`await device.getEndpoint(1).write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f});`
for my QBKG26LM (lumi.switch.n3acn3) to make it report actions when in decoupled mode. It does also report when *not* in decoupled mode though.

I'm not using the manufacturer code firmware given above as I'm using a raspBee II as my adapter.

Also, I note that the documentation page for the QBKG26LM seems to have incorrect information regarding the setting of the decoupled mode in MQTT. Probably should note that the alternate instructions for QBKG25LM also applies to QBKG26LM .

**Comment by balonchiks** [comment] 2021-06-28 09:33
> 
> Am I correct that I need re-flash my coordinator?
> 
if you are using stick v3 from modkam.ru then yes, you need to flash it with [this](https://github.com/Koenkk/zigbee-herdsman-converters/issues/1986#issuecomment-778337754) firmware

**Comment by skyksandr** [comment] 2021-06-28 10:39
@balonchiks I'm using cc2531 stick flashed with coordinator firmware.

@ruifung do you mean:
```
zigbee2mqtt/<device_id>/set
{"operation_mode_right": "decoupled"}
```
or
```
zigbee2mqtt/<device_id>/right/set
{
  "operation_mode": {
    "state": "decoupled"
  }
}
```
If that makes any difference.

**Comment by lovelylain** [comment] 2021-06-28 12:30
@skyksandr No need to re-flash your coordinator. Koenkk only fixed for QBKG25LM, if your device is QBKG26LM, please wait or modify by yourself.

**Comment by Koenkk** [comment] 2021-06-28 15:41
Merged https://github.com/Koenkk/zigbee-herdsman-converters/pull/2734 assuming this can be closed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Closed by Koenkk** 2021-06-28 15:41 UTC

**Comment by ruifung** [comment] 2021-06-28 18:44
Just because it's somewhat related to this, #2735 should also fix the wierdness in the operation_mode states (and outright not being able to /get them). Now I can check if the switch is decoupled before doing anything for the action.

**Comment by skyksandr** [comment] 2021-06-29 10:39
@Koenkk, @ruifung Thank you guys! It is now working! Owe you guys a 🍻

**Comment by redesigndavid** [comment] 2021-07-06 23:19
Just want to say huge thanks @Koenkk

**Comment by Koenkk** [comment] 2021-07-07 15:52
@redesigndavid all credits go to @ruifung

**Comment by slydiman** [comment] 2021-07-07 18:19
> Appreciate your efforts but since I already put too much time into this issue and I don't see anything different in your sniffs I don't want to continue further on it.

> reopened this on 9 Feb

> reopened this on 5 May

😄

**Comment by SHOOTnick1985** [comment] 2021-12-20 10:53
@Koenkk hi!

The Aqara D1 switch QBKG26LM don't work with action: hold, triple and release for all button. Work only single and double.
Can you help with this?

**Comment by ASAujla** [comment] 2022-10-27 20:11
Hi all, I have just installed a QBKG26LM and I am struggling to get actions working, too. I am running the Z2M Home Assistant Add-on and a ConBee2 stick. As I understand it, I need to:
1) Unpair the QBKG26LM,
2) Change the firmware of the ConBee2 to one that will trick the QBKG26LM into thinking that it is an Aqara coordinator,
3) Pair the QBKG26LM again,
4) Revert back to the original ConBee2 firmware.

Is my understanding correct? How would I go about finding/creating the new firmware for the ConBee2 and subsequently reinstalling the original firmware? Will doing so wipe my existing Zigbee network?

Apologies for sounding like I need for this to be explained to me like I'm five years old, but this unfortunately is the case here.

**Comment by ruifung** [comment] 2023-07-13 11:33
> Energy is not displayed on the qbkg26lm device. Zigbee2mqtt version 1.32.1-1.
@kondrikserg Please open a new issue instead of adding a comment here.
