### ISSUE TITLE
Door and Window Sensor ZM-CG205

### ISSUE THREAD

**Issue by klio-klio** [Koenkk/zigbee-herdsman-converters#2832] opened 2021-07-24 10:08 UTC
Hello.
I got a door and a window sensor.
Unfortunately it is not supported by zigbee2mqtt. Maybe already has a converter for it? On the packaging there is a different type designation than in the instruction leaflet (ZM-CG205)

![IMG_20210721_151339](https://user-images.githubusercontent.com/76972213/126865162-a85428cd-7af7-430c-a7e6-39c894a4f9a0.jpg)
![image](https://user-images.githubusercontent.com/76972213/126865175-6847ca64-6fa3-4853-97fd-7ea998265599.png)
![image](https://user-images.githubusercontent.com/76972213/126865217-4f038b66-bdd1-4a7c-8b2c-b83f205b5492.png)

**Comment by klio-klio** [comment] 2021-07-24 10:27
Maybe that helps. It is recognized in ZHA
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=0, maximum_buffer_size=80, maximum_incoming_transfer_size=160, server_mask=10752, maximum_outgoing_transfer_size=160, descriptor_capability_field=<DescriptorCapability.0: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0402",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0500"
      ],
      "out_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0500"
      ]
    }
  },
  "manufacturer": "_TYZB01_xph99wvr",
  "model": "TS0203",
  "class": "zigpy.device.Device"
}

**Comment by Koenkk** [comment] 2021-07-24 12:51
Dupe of https://github.com/Koenkk/zigbee2mqtt/issues/7553

**Closed by Koenkk** 2021-07-24 12:51 UTC
