### ISSUE TITLE
Lonsonho 2-gang wall switch is recognized as a curtain motor (TS0601)

### ISSUE THREAD

**Issue by Foroxon** [Koenkk/zigbee-herdsman-converters#1324] opened 2020-06-17 18:12 UTC
A brand new model of Lonsonho 2-gang wall switch after pairing with a coordinator is recognized as a curtain motor (TS0601).
Could you please help me to configure it like a switch?
I found a manual on how to add a new device but didn't find anything about wrong recognized devices.

**Comment by Koenkk** [comment] 2020-06-17 18:46
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/3729, proposed a possible solution here: https://github.com/Koenkk/zigbee2mqtt/issues/3729#issuecomment-643610007

**Closed by Koenkk** 2020-06-17 18:46 UTC
