### ISSUE TITLE
Adeo ZBEK-29 - Not supported

### ISSUE THREAD

**Issue by Ajhomepn** [Koenkk/zigbee-herdsman-converters#6428] opened 2023-11-07 09:17 UTC
Hi, 

My deeply apologies, i'm aware that i'm not following the right path asking for support where. 

I have a light panel from Adeo , the ZBEK-29. I can connect it to zigbee2mqtt but it shows as "Not supported".
![Capture](https://github.com/Koenkk/zigbee2mqtt.io/assets/146856023/f19cbb4d-e4f4-475e-b174-b447159c8f00)

I have a similar product , the Adeo ZBEK-27 and it work's perfectly.

I understand if you can't support due to the fact that I have not done the initial step's of the https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html; there is any video to support the guys that are not soo tech savvy ? 

Thank you for your time,

**Comment by polumi** [comment] 2023-11-11 10:07
> Please provide a link to the device.
[
](https://www.leroymerlin.es/productos/iluminacion/iluminacion-interior/iluminacion-para-cocina/paneles-led-de-cocina/panel-led-inspire-gdansk-4000lm-rgb-w-contectado-120x30-cm-84845509.html?src=clk)

**Comment by Koenkk** [comment] 2023-11-12 08:00
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/19610 (device already added)

**Closed by Koenkk** 2023-11-12 08:00 UTC
