### ISSUE TITLE
Tuya "Smart air box"

### ISSUE THREAD

**Issue by meisterlampe** [Koenkk/zigbee-herdsman-converters#2583] opened 2021-05-16 11:25 UTC
Hi, 

i just bought a _Tuya "Smart Air Box"_ from [Aliexpress](https://de.aliexpress.com/item/1005002461457617.html?spm=a2g0s.9042311.0.0.9f324c4dCSKULa)

Joining the network was no problem, but the device doesn't seem to have a converter yet and I wanted to add it to this great project.
Unfortunately, I'm a bit lost right now.

Ok, so here is what I figured out by following your Guide [How to support new Tuya devices](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_tuya_devices.html):

- Model-ID: 'TS0601'
- Manufacturer-Name: '_TZE200_8ygsuhe1'
- Vendor: I have no idea O:-) This is not mentioned anywhere on the box or the device itself. Maybe the numbers on the board do give some hint? (see pictures at the end)

I added the external converter and got the following output:
```
Zigbee2MQTT:debug 2021-05-16 10:05:52: Received Zigbee message from '0x60a423fffed20ff6', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,0,2],"type":"Buffer"},"datatype":2,"dp":22,"fn":0,"status":0,"transid":2}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-16 10:05:52: Received Zigbee message from '0x60a423fffed20ff6', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,0,1],"type":"Buffer"},"datatype":2,"dp":21,"fn":0,"status":0,"transid":2}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-16 10:05:52: Received Zigbee message from '0x60a423fffed20ff6', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,1,115],"type":"Buffer"},"datatype":2,"dp":2,"fn":0,"status":0,"transid":2}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-16 10:05:53: Received Zigbee message from '0x60a423fffed20ff6', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,0,217],"type":"Buffer"},"datatype":2,"dp":18,"fn":0,"status":0,"transid":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-16 10:05:53: Received Zigbee message from '0x60a423fffed20ff6', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,2,223],"type":"Buffer"},"datatype":2,"dp":19,"fn":0,"status":0,"transid":0}' from endpoint 1 with groupID 0
```

By using your [read_tuya_dump-Script](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/scripts/read_tuya_dump.py) and the given parsers I coudl easily figure out, that data point 18 should be the temperature. 

```
2021-05-16T12:05:52 0x60a423fffed20ff6 (tid:   2, s: 0) [DP22] => 0 2
2021-05-16T12:05:52 0x60a423fffed20ff6 (tid:   2, s: 0) [DP21] => 0 1
2021-05-16T12:05:52 0x60a423fffed20ff6 (tid:   2, s: 0) [DP2] => 0 371
2021-05-16T12:05:53 0x60a423fffed20ff6 (tid:   0, s: 0) [SmartAirBox Temperature] => 0 21.7°C
2021-05-16T12:05:53 0x60a423fffed20ff6 (tid:   0, s: 0) [DP19] => 0 735
```

But now I'm a bit stuck. As of the article description the other values should represent:
- Formaldehyde: 0-10.0 (mg/m3)
- VOC: 0-99.9 (ppm)
- Carbon dioxide: 0-1000 (ppm)
- Humidity: 0-95 (%) 

I got the humidity from another sensor and it should be about 60%, but I have no idea how to move on.
It would be nice, if someone could help me out. 👍 

Here are some shots of the device:
![IMG_20210516_124242](https://user-images.githubusercontent.com/16793613/118394608-0010d080-b646-11eb-8a1f-b77268e4388f.jpg)
![IMG_20210516_124353](https://user-images.githubusercontent.com/16793613/118394616-099a3880-b646-11eb-9916-128ac1ea0a75.jpg)
![IMG_20210516_124402](https://user-images.githubusercontent.com/16793613/118394618-0bfc9280-b646-11eb-9426-f4dd73c0dd52.jpg)
![IMG_20210516_114538](https://user-images.githubusercontent.com/16793613/118394625-10c14680-b646-11eb-88db-97b7cebb555a.jpg)
![IMG_20210516_114503](https://user-images.githubusercontent.com/16793613/118394627-128b0a00-b646-11eb-9683-7a1785eb4842.jpg)

Thanks in advance :-)

**Comment by Koenkk** [comment] 2021-05-16 14:18
Duplicate of https://github.com/Koenkk/zigbee2mqtt/discussions/7299

**Closed by Koenkk** 2021-05-16 14:18 UTC
